logging.level.ge.crud.company.controller=debug
# datasource config
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=cerdunia
spring.datasource.driver-class-name=org.postgresql.Driver
# additional config of hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=crud

logging.level.root=debug